spring.application.name=weather-dashboard

weather.api.url = ${WEATHER_API_URL}
weather.api.key = ${WEATHER_API_TOKEN}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.datasource.url=jdbc:postgresql://localhost:5432/weather_db
# spring.datasource.username=postgres
# spring.datasource.password=177013
# spring.jpa.hibernate.ddl-auto=update

# weather.api.url = https://api.weatherapi.com/v1/current.json
# weather.api.key = 6cdd0449d15e488a9f792119250312